"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

final_space = true
shell_integration = true
enable_cursor_positioning = true
async = true
version = 4

[[blocks]]
  type = "rprompt"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "yellow"
    background = "transparent"

    [blocks.segments.options]
      threshold = 1000
      style = "roundrock"

[[blocks]]
  type = "prompt"
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "blue"
    background = "transparent"

    template = "{{ .Path }}"

    [blocks.segments.options]
      style = "full"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "white"
    background = "transparent"

    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <red>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"

    [blocks.segments.options]
      fetch_status = true
      fetch_push_status = true
      branch_icon = ""

[[blocks]]
  type = "prompt"
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = "transparent"

    template = "❯"
