"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

final_space = true
shell_integration = true
enable_cursor_positioning = true
async = true
version = 4

[palette]
  main = "#FF66FF"
  secondary = "#6666FF"
  neutral = "#EEEEEE"

  good = "#66FF66"
  bad = "#FF6666"
  notice = "#FFFF66"

  none = "transparent"

[var]
  PromptIcon = "❯"

[[blocks]]
  type = "rprompt"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:notice"
    background = "p:none"

    [blocks.segments.options]
      threshold = 1000
      style = "roundrock"

[[blocks]]
  type = "prompt"
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:secondary"
    background = "p:none"

    template = "{{ .Path }}"

    [blocks.segments.options]
      style = "full"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:neutral"
    background = "p:none"

    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:notice>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"

    [blocks.segments.options]
      fetch_status = true
      fetch_push_status = true
      branch_icon = ""

[[blocks]]
  type = "prompt"
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{if gt .Code 0}}p:bad{{end}}",
      "{{if eq .Code 0}}p:main{{end}}",
    ]
    background = "p:none"

    template = "{{ .Var.PromptIcon }}"

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:bad{{end}}",
    "{{if eq .Code 0}}p:main{{end}}",
  ]
  background = "p:none"

  template = "{{ .Var.PromptIcon }} "

[secondary_prompt]
  foreground = "p:main"
  background = "p:none"

  template = "{{ .Var.PromptIcon }}{{ .Var.PromptIcon }} "
